const desert = [

    {
        "name" : "Wild Bactrian Camel",
        "region" : "desert",
        "type" : "mammal",
        "diet" : "herbivore",
        "population" : 600,
        "status" : "critically endangered",
        "lifespan" : 50,
        "weight": 48000,
        "body-length": 1828,
        "top-speed": 65,
        "facts": ["Until recently, wild Bactrian camels were thought to have descended from domesticated Bactrian camels that became feral after being released into the wild. However, genetic studies have established it as a separate species which diverged from the Bactrian camel about 1.1 million years ago", "They travel with a single adult male in the lead and assemble near water points where larger groups can also be seen.", "Wild Bactrian camels travel over long distances, seeking water in places close to mountains where springs are found, and hill slopes covered in snow provide some moisture in winter."],
        "images": ["https://www.britannica.com/explore/savingearth/wp-content/uploads/sites/4/2020/04/bactrian-2.jpg", "https://julieburton.blog/wp-content/uploads/2018/06/camel.jpg"], 
    },
    {
        "name" : "Giant Hairy Desert Scorpion",
        "region" : "desert",
        "type" : "arachnid",
        "diet" : "carnivore",
        "population" : 54000,
        "status" : "stable",
        "lifespan" : 20,
        "weight": 7,
        "body-length": 140,
        "top-speed": 8,
        "facts": ["Its diet consists of large insects, spiders, and small vertebrates. This is an aggressive and active scorpion, which, as with all scorpions, is nocturnal.", "Like all scorpions, the giant desert hairy scorpion gives birth to live young, which remain on the mother's back for a week or more before leaving.", "They are usually found in and around washes or low-elevation valleys where they dig elaborate burrows (up to 2.5 m or 8 ft 2 in) and emerge at night to forage for prey and mates.", "This isnt really a fact. Consider it an Easter Egg. You werent really supposed to see it. Who knew eh?"],
        "images": ["https://arachnoboards.com/gallery/one-of-a-kind-hadrurus-arizonensis.42325/full?d=1499562743", "https://thumbs.dreamstime.com/z/hadrurus-arizonensis-scorpion-giant-desert-lives-areas-107131836.jpg"], 
    },
    {
        "name" : "Fennec Fox",
        "region" : "desert",
        "type" : "carnivore",
        "diet" : "carnivore",
        "population" : 400000,
        "status" : "stable",
        "lifespan" : 11,
        "weight": 1600,
        "body-length": 200,
        "top-speed": 40,
        "facts": ["Fennec foxes have extraordinary hearing to locate underground prey.", "Their large ears, which are usually 4 to 6 inches long, help to dissipate excess body heat on hot days.", "The fennec fox appears to be the only carnivore in the Sahara Desert able to live without freely available water."],
        "images": ["https://www.treehugger.com/thmb/58w8Lf8eBqMbFx5XrbCMsRj1Kdg=/3872x2592/filters:no_upscale():max_bytes(150000):strip_icc()/fennec-fox-85120553-7606608314bf477b8dbcd76b4346e0cf.jpg", "https://upload.wikimedia.org/wikipedia/commons/9/9c/Fennec_Fox.jpg"], 
    },
    {
        "name" : "Sand Cat",
        "region" : "desert",
        "type" : "mammal",
        "diet" : "carnivore",
        "population" : 27000,
        "status" : "endangered",
        "lifespan" : 13,
        "weight": 2800,
        "body-length": 5100,
        "top-speed": 40,
        "facts": ["Sand cats are the only cats that live in the desert.", "Sand cats don't make many sounds, but when they do, it's not the sound you'd expect. When taking a break from its solitary lifestyle and looking for a mate, the sand cat uses mews and bark-like vocalizations"],
        "images": ["https://cdn.zmescience.com/wp-content/uploads/2013/10/sand-cat.jpg", "https://images.newscientist.com/wp-content/uploads/2016/08/05172510/b5dbhp.jpg"], 
    },
    {
        "name" : "South African Lion",
        "region" : "desert",
        "type" : "mammal",
        "diet" : "carnivore",
        "population" : 15000,
        "status" : "endangered",
        "lifespan" : 15,
        "weight": 14300,
        "body-length": 3000,
        "top-speed": 81,
        "facts": ["Lions are the largest predators in Africa.", "They are also the most sociable of the cat family and can live in prides of up to 20 and more", "Males of about two and a half years and older are driven out of the pride and also out of the pride territory by the territorial dominant adult lions.", "Some prides will also wander for a long period of time without settling into a territory."],
        "images": ["https://149366112.v2.pressablecdn.com/wp-content/uploads/2020/07/shutterstock_555551179-scaled.jpg", "https://cdn.thelondoneconomic.com/wp-content/uploads/2018/02/lion-3040797_1920.jpg"], 
    },
    {
        "name" : "Coyote",
        "region" : "desert",
        "type" : "mammal",
        "diet" : "carnivore",
        "population" : 45000,
        "status" : "stable",
        "lifespan" : 15,
        "weight": 21000,
        "body-length": 8600,
        "top-speed": 69,
        "facts": ["Coyotes are members of the dog family (canids) which includes wolves, jackals, coyotes, dogs, and foxes.", "Coyotes are carnivorous (eat meat) -- they eat primarily small mammals, such as eastern cottontail rabbits, thirteen-lined ground squirrels, and white-footed mice. They occasionally eat birds, snakes, large insects and other large invertebrates."],
        "images": ["https://bloximages.newyork1.vip.townnews.com/theadvocate.com/content/tncms/assets/v3/editorial/0/63/063b23f8-fd5c-5de6-96f4-0744dcb524fc/5feba36d73ca9.image.jpg?resize=1024%2C682", "https://upload.wikimedia.org/wikipedia/commons/9/9c/2009-Coyote-Yosemite.jpg"], 
    },
    {
        "name" : "Desert Tortoise",
        "region" : "desert",
        "type" : "reptile",
        "diet" : "herbivore",
        "population" : 100000,
        "status" : "stable",
        "lifespan" : 100,
        "weight": 8000,
        "body-length": 3500,
        "top-speed": 0.3,
        "facts": ["The desert tortoise is herbivorous, feeding mostly on native grasses, leafy plants and flowers.", "Desert tortoises can live in areas with ground temperatures exceeding 60 °C (140 °F) because of their ability to dig burrows and escape the heat. At least 95% of their lives are spent in burrows."],
        "images": ["https://srel.uga.edu/wp-content/uploads/sites/49/2019/12/2556-5-copy.jpg", "https://defenders.org/sites/default/files/styles/meta_image/public/2019-04/desert_tortoise_dan_fillipi_header.jpg?itok=gUiY2w3K"], 
    },
    {
        "name" : "Bearded Dragon",
        "region" : "desert",
        "type" : "reptile",
        "diet" : "omnivore",
        "population" : 1000000,
        "status" : "extinct",
        "lifespan" : 15,
        "weight": 510,
        "body-length": 600,
        "top-speed": 15,
        "facts": ["Beardies wave their arms at each other to show species recognition or to demonstrate submission.", "Bearded dragons can run up to nine miles per hour. But for the most part, they are quite sedentary lizards.", "Bearded dragons are one of the most easy-going and relaxed in the reptile world. They are amongst the easiest to leash train, and will even casually allow their owners to dress them in clothing.", "Bearded dragon is only on this list because one of the developers owns one. Otherwise, there is no reason for this reptile to be on this list. This is purely here to appease you, Graeme!"],
        "images": ["https://www.everythingreptiles.com/wp-content/uploads/2020/03/Two-Bearded-Dragon-Babies.jpg", "https://www.zillarules.com/-/media/Images/Zilla-NA/US/Blog-Articles/myths-facts-about-bearded-dragon-care/bearded-dragon.jpg"], 
    },
    {
        "name" : "Desert Bighorn Sheep",
        "region" : "desert",
        "type" : "mammal",
        "diet" : "herbivore",
        "population" : 70000,
        "status" : "stable",
        "lifespan" : 20,
        "weight": 70000,
        "body-length": 1850,
        "top-speed": 24,
        "facts": ["Bighorn sheep live in the Rocky Mountain region of North America, ranging from Mexico, northward across the western United States and into Canada. They live in the rocky areas, balancing on the boulders with their hooves, which are rough on the bottom to give the sheep more traction.", "Bighorn sheep have very good eyesight, which allows them to judge distances accurately when jumping.", "Herds are separated by gender. Females live in nursery herds, with five to 100 members, which include adult females and lambs of both genders. Male-only bachelor herds usually contain five to 50 rams at one time."],
        "images": ["https://www.visitcalifornia.com/sites/visitcalifornia.com/files/styles/welcome_image/public/VC_DeathValleyFloraFauna_Module1_BigHornSheep_Stock_RF_479076538_1280x640.jpg", "https://www.livingdesert.org/site/assets/files/1944/bighorn_sheep.600x400.jpg"], 
    },
    {
        "name" : "Pronghorn",
        "region" : "desert",
        "type" : "mammal",
        "diet" : "herbivore",
        "population" : 1000000,
        "status" : "stable",
        "lifespan" : 10,
        "weight": 60000,
        "body-length": 1500,
        "top-speed": 90,
        "facts": ["The pronghorn is a unique North American mammal. Its Latin name, Antilocapra americana, means 'American goat-antelope,' but it is not a member of the goat or the antelope family and it is not related to the antelopes found in Africa.", "The pronghorn is the only surviving member of the Antilocapridae family and it has been in North America for over a million years!", "The pronghorn is the fastest animal in the Western Hemisphere. It can run at speeds of up to 60 miles per hour and it can run long distances at speeds of 30-40 miles per hour. It can make bounds of up to 20 feet when it is running."],
        "images": ["https://files.worldwildlife.org/wwfcmsprod/images/Pronghorn/story_full_width/9q8s8x88yq_shutterstock_122538310.jpg", "https://upload.wikimedia.org/wikipedia/commons/a/a3/Antilocapra_americana.jpg"], 
    },
    {
        "name" : "Tiger Rattlesnake",
        "region" : "desert",
        "type" : "reptile",
        "diet" : "carnivore",
        "population" : 2000000,
        "status" : "stable",
        "lifespan" : 20,
        "weight": 1200,
        "body-length": 2000,
        "top-speed": 29,
        "facts": ["Tiger rattlesnakes are terrestrial snakes and are nocturnal during the hot summer (June–August), but become diurnal and crepuscular during the fall season. They hibernate during the late fall and winter in rock crevices or animal burrows.", "Rattlesnakes are well known for the namesake “rattles” found at the end of their tales. The rattle is made up of various interlocking rings of keratin, the same material that human hair, skin, and nails are made of." , "Once rattlesnakes grow out of their old skin and go through the molting process, their bodies naturally add an extra segment to their rattles each time.", "Unlike grass snakes, rattlesnakes have vertical pupils in their eyes, similar to cats' eyes."],
        "images": ["https://www.thoughtco.com/thmb/oXgaJDvwmajpxhIMgiZBXtuHl9k=/2121x1193/smart/filters:no_upscale()/GettyImages-737142063-0603f1327ee840a5a0f46b044a0a36f6.jpg", "https://cdn.britannica.com/s:800x450,c:crop/69/188769-138-B2D4A0F4/rattle-rattlesnake.jpg"], 
    },
  
    {
        "name" : "Sandfish Skink",
        "region" : "desert",
        "type" : "reptile",
        "diet" : "carnivore",
        "population" : 50000,
        "status" : "stable",
        "lifespan" : 3,
        "weight": 15,
        "body-length": 20,
        "top-speed": 10,
        "facts": ["The Sandfish can live on both lands and in water. This reptile species can protect itself from predators as they have the ability to camouflage. The sandfish skink is an extremely intelligent creature.", "The sandfish skink mostly spends its lifetime in the burrows across desert regions of North Africa. The sandfish skinks always burrow themselves in the sand and escape from predators. This reptile species likes to live in sand and high temperatures."],
        "images": ["https://media.kidadl.com/medium_60cb6ab394ac670fa5e774b1_sandfish_facts_about_the_sand_dwelling_lizard_of_family_scincidae_51b5fdca85.jpg", "https://www.snaketracks.com/wp-content/uploads/2020/04/SandFish-Skink-1.jpg"], 
    },

]