const Tundra = [

{
    "name" : "Lemmings",
    "region" : "tundra",
    "type" : "mammal",
    "diet" : "herbivore",
    "population" : 1500,
    "status" : "stable",
    "lifespan" : 2,
    "weight": 30,
    "body-length": 180,
    "top-speed": 4.8,
    "facts": ["Lemming needs to eat 6 hours per day due to low caloric value of plants that it usually consumes. Their diet is made up of leaves, shoots, bulbs, grasses and they occasionally store food for the winter", "Natural enemies of lemmings are birds of prey (owls, hawks, gyrfalcons), foxes, wolves and stoats.", "Lemmings go through periodic crash and boom cycles (every 3-4 years)."],
    "images": ["https://inaturalist-open-data.s3.amazonaws.com/photos/22672833/medium.jpg", "https://static.inaturalist.org/photos/41601458/medium.jpeg"], 
},
{
    "name" : "Reindeer",
    "region" : "tundra",
    "type" : "mammal",
    "diet" : "herbivore",
    "population" : 235000,
    "status" : "stable",
    "lifespan" : 7,
    "weight": 35000,
    "body-length": 2800,
    "top-speed": 50,
    "facts": ["They migrate over 2,400 km a year which is the longest land migration route of any land mammal on Earth", "Reindeer eat mosses, herbs, ferns, grasses, and the shoots and leaves of shrubs and trees, especially willow and birch. In winter, they make do with lichen (also called reindeer moss) and fungi, scraping the snow away with their hooves to get it", "Both male and female reindeer grow antlers, while in most other deer species, only the males have antlers."],
    "images": ["https://www.science.org/do/10.1126/science.aay4606/abs/reindeer_16x9.jpg", "https://static.wikia.nocookie.net/planetzoo/images/e/ec/Reindeer.jpg/revision/latest?cb=20191218070130"], 
},

{
    "name" : "Arctic Hare",
    "region" : "tundra",
    "type" : "mammal",
    "diet" : "herbivore",
    "population" : 1500,
    "status" : "stable",
    "lifespan" : 1.5,
    "weight": 5500,
    "body-length": 700,
    "top-speed": 60,
    "facts": ["Even though they do not hibernate during the winter, Arctic hares occasionally gather in groups in the underground burrows to keep each other warm.", "When resting, Arctic hares maintain a nearly spherical shape and typically stay in groups, but do not huddle.", "The hares eat woody plants, mosses, and lichens which they may dig through the snow to find in winter. In other seasons they eat buds, berries, leaves, roots, and bark"],
    "images": ["https://i.pinimg.com/originals/28/70/e9/2870e9126a1da4fbcea586595b3827f0.jpg", "https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/wild-arctic-hare-roberto-marchegiani.jpg"], 
},
{
    "name" : "Squirrel",
    "region" : "tundra",
    "type" : "mammal",
    "diet" : "herbivore",
    "population" : 2000,
    "status" : "stable",
    "lifespan" : 10,
    "weight": 1500,
    "body-length": 495,
    "top-speed": 32,
    "facts": ["In the summer it forages for tundra plants, seeds, and fruit to increase body fat for its winter hibernation", "Communication between squirrels is done through both vocal and physical means. When they meet, nose to nose contact is made or other body parts are pressed together. The 'tsik-tsik' calls are made in response to threats and vary as between different predators. Deep guttural sounds are used to indicate land-based predators while short band whistle chatter indicates danger from the air."],
    "images": ["https://cdn.britannica.com/41/66141-004-3B817DDD.jpg", "https://m.psecn.photoshelter.com/img-get/I0000ugwpD.FL38w/s/800/700/95123-17.jpg"], 
},
{
    "name" : "Arctic Fox",
    "region" : "tundra",
    "type" : "mammal",
    "diet" : "carnivore",
    "population" : 110000,
    "status" : "stable",
    "lifespan" : 11,
    "weight": 9400,
    "body-length": 6800,
    "top-speed": 50,
    "facts": ["The Arctic fox preys on many small creatures such as lemmings, voles, ringed seal pups, fish, waterfowl, and seabirds", "Arctic foxes must endure a temperature difference of up to 90–100 °C (160–180 °F) between the external environment and their internal core temperature.[14] To prevent heat loss, the Arctic fox curls up tightly tucking its legs and head under its body and behind its furry tail.", ""],
    "images": ["https://upload.wikimedia.org/wikipedia/commons/e/e2/Alopex_lagopus_IMG_9019.JPG", "https://cdn.hswstatic.com/gif/arctic-fox-1.jpg"], 
},
{
    "name" : "Polar Bear",
    "region" : "tundra",
    "type" : "mammal",
    "diet" : "omnivore",
    "population" : 30000,
    "status" : "endangered",
    "lifespan" : 25,
    "weight": 600000,
    "body-length": 2750,
    "top-speed": 40,
    "facts": ["Polar bears are classified as marine mammals.", "Polar Bears are actually black, note white. Polar bear fur is translucent, and only appears white because it reflects visible light. Beneath all that thick fur, their skin is jet black.", "They can swim constantly for days.", "Scientists can extract the DNA of a Polar Bear and the seal it ate for lunch through its footprints in the snow"],
    "images": ["https://images.unsplash.com/photo-1589656966895-2f33e7653819?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80", "https://images.unsplash.com/photo-1553425300-8bd56360f8eb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80"], 
},
{
    "name" : "Arctic Wolves",
    "region" : "tundra",
    "type" : "mammal",
    "diet" : "carnivore",
    "population" : 200000,
    "status" : "stable",
    "lifespan" : 7,
    "weight": 40000,
    "body-length": 1828,
    "top-speed": 46,
    "facts": ["Wolf pups are born with blue irises that change to yellow as they grow older.", "The layer of fur closest to the wolf's skin is waterproof.","The fastest recorded speed of an Arctic Wolf is 46 mph"],
    "images": ["http://justfunfacts.com/wp-content/uploads/2017/01/arctic-wolf.jpg", "https://images.fineartamerica.com/images-medium-large-5/arctic-wolves-pack-in-wildlife-winter-4fr.jpg"], 
},
{
    "name" : "Snowy Owl",
    "region" : "tundra",
    "type" : "bird",
    "diet" : "carnivore",
    "population" : 257000,
    "status" : "stable",
    "lifespan" : 10,
    "weight": 2000,
    "body-length": 730,
    "top-speed": 46,
    "facts": ["Snowy Owls have feet covered in feathers like fluffy slippers. This provides ample insulation for the cold arctic climate.", "Snowy Owls swallow small prey such as Lemmings, whole.","Unlike most owls which are nocturnal, Snowy Owls are diurnal meaning they hunt during daylight."],
    "images": ["https://farm9.staticflickr.com/8659/16167077194_d4a7a433d8_b.jpg", "https://farm5.staticflickr.com/4063/4302380736_9e03d2cdc7_b.jpg"], 
},
{
    "name" : "Loon",
    "region" : "tundra",
    "type" : "bird",
    "diet" : "carnivore",
    "population" : 640000,
    "status" : "stable",
    "lifespan" : 30,
    "weight": 5500,
    "body-length": 810,
    "top-speed": 100,
    "facts": ["Loons find their prey by sight. They eat mainly fish, supplemented with amphibians, crustaceans and similar mid-sized aquatic fauna. Specifically, they have been noted to feed on crayfish, frogs, snails, salamanders and leeches. They prefer clear lakes because they can more easily see their prey through the water.", "Loons are excellent divers, they can plunge over 200 feet below the water’s surface.", "Most loons need a long water runway in order to take off due to their body shape and size."],
    "images": ["https://upload.wikimedia.org/wikipedia/commons/e/ef/PacificLoon24.jpg", "https://images.squarespace-cdn.com/content/v1/502bf11ce4b04c0138eda663/1595096901317-A3S5WXNXQITYTRR5QE98/Running+Loon+Takeoff.jpg"], 
},
{
    "name" : "Musk Ox",
    "region" : "tundra",
    "type" : "mammal",
    "diet" : "herbivore",
    "population" : 125000,
    "status" : "stable",
    "lifespan" : 20,
    "weight": 410000,
    "body-length": 1500,
    "top-speed": 60,
    "facts": ["Their name comes from the fact that they emit a strong smell during the mating season.", "Muskoxen eat a wide variety of plants, including grasses, sedges, forbs, and woody plants. These creatures are poorly adapted for digging through heavy snow for food, so winter habitat is generally restricted to areas with shallow snow accumulations or areas blown free of snow.", "These bulky animals can stay in the Arctic all year round, surviving temperatures of -70 degrees centigrade."],
    "images": ["https://animalcorner.org/wp-content/img/muskox.jpg", "https://returntonow.net/wp-content/uploads/2020/12/j-1.jpg"], 
},
{
    "name" : "Penguin",
    "region" : "tundra",
    "type" : "bird",
    "diet" : "carnivore",
    "population" : 460000,
    "status" : "stable",
    "lifespan" : 20,
    "weight": 45000,
    "body-length": 1300,
    "top-speed": 9,
    "facts": ["Emperors feed mostly on Antarctic silverfish as well as other species of fish, krill and some squid", "An adult penguin eats about 2-3 kg per day, but on a good day they can eat twice this much to build up their store of body fat for the long winter, or for feeding their chicks.", "Emperor penguins are the Olympic divers of the bird world. The deepest recorded dive was 564 m – that’s the equivalent of nearly 2 x the height of the Shard, Europe’s tallest building. And the longest recorded dive was nearly 28 minutes. That’s incredible!", ""],
    "images": ["https://res.cloudinary.com/uktv/image/upload/h_720,q_80,w_1280/v1394211284/vkruxigtvcpkkwm6smqu.jpg", "https://upload.wikimedia.org/wikipedia/commons/a/a3/Aptenodytes_forsteri_-Snow_Hill_Island%2C_Antarctica_-adults_and_juvenile-8.jpg"], 
},
{
    "name" : "Mountain Goat",
    "region" : "tundra",
    "type" : "mammal",
    "diet" : "herbivore",
    "population" : 100000,
    "status" : "stable",
    "lifespan" : 12,
    "weight": 136000,
    "body-length": 1778,
    "top-speed": 24,
    "facts": ["Mountain goats can jump 12 feet in one leap.", "A mountain goats' white coat has a double layer that sheds in the summer and provides warmth in the winter.", "Mountain goats are not in the same genus as goats. In the bovidae family, mountain goats are associated with antelopes, gazelles and cattle.", "Mountain goats live in alpine and subalpine environments. In the high-altitude environments, sometimes above 13,000 ft, they are the largest mammal. The high elevation protects mountain goats from predators"],
    "images": ["https://www.nationalforests.org/assets/images/1280px-Mountain_Goat_USFWS.jpg", "https://www.nationalforests.org/assets/images/_1600x1600_fit_center-center_80_none/Okanogan-Wenatchee_Alpine-Lakes-Wilderness_Traute-Parrie.JPG"], 
},
{
    "name" : "Rock Ptarmigan",
    "region" : "tundra",
    "type" : "bird",
    "diet" : "omnivore",
    "population" : 8000000,
    "status" : "stable",
    "lifespan" : 2,
    "weight": 540,
    "body-length": 350,
    "top-speed": 7.5,
    "facts": ["Rock Ptarmigan eat mostly plant buds, catkins, leaves, flowers, small twigs, berries, and seeds. They also consume spiders, insects, and occasionally snails, taken from the ground, from snow, and from low vegetation.", ""],
    "images": ["https://cdn.download.ams.birds.cornell.edu/api/v1/asset/163985621/1800", "https://m.psecn.photoshelter.com/img-get/I0000l37Xa6yvEZg/s/1200/I0000l37Xa6yvEZg.jpg"], 
},
{
    "name" : "Wolverine",
    "region" : "tundra",
    "type" : "mammal",
    "diet" : "carnivore",
    "population" : 300,
    "status" : "stable",
    "lifespan" : 13,
    "weight": 25000,
    "body-length": 1100,
    "top-speed": 50,
    "facts": ["The Wolverine is a muscular and stocky carnivore which actually resembles a small bear.", "The adult Wolverine is about the size of a medium dog"],
    "images": ["https://factanimal.com/wp-content/uploads/2018/09/wolverine-woods.jpg", "https://i.pinimg.com/originals/23/9a/5b/239a5b9a3d5033d85aa31b795a5d3757.jpg"], 
},
{
    "name" : "Domestic Yak",
    "region" : "tundra",
    "type" : "mammal",
    "diet" : "herbivore",
    "population" : 12000000,
    "status" : "stable",
    "lifespan" : 20,
    "weight": 580000,
    "body-length": 3300,
    "top-speed": 40,
    "facts": ["Yaks live at the highest altitude of any mammal.", "At night and in snowstorms they will protect themselves from the cold by huddling up together with their calves in the warmer centre.", "Yaks have firm, dense horns which they use to break through snow in order to get the plants that are buried underneath. They will also use their horns in defence."],
    "images": ["https://animalia.us-east-1.linodeobjects.com/animals/photos/full/1.25x1/41WMThjlxVrMCla3kJSn.jpg", "https://ichef.bbci.co.uk/news/976/cpsprodpb/13D96/production/_106920318_gettyimages-630124130.jpg"], 
},
{
    "name" : "Walrus",
    "region" : "tundra",
    "type" : "mammal",
    "diet" : "carnivore",
    "population" : 250000,
    "status" : "stable",
    "lifespan" : 40,
    "weight": 1000000,
    "body-length": 3600,
    "top-speed": 35,
    "facts": ["They live in shallow water but dive deeper in search of food", "Both male and female walrus have large tusks.", "They can weigh as much as a small car!"],
    "images": ["https://assets.londonist.com/uploads/2018/04/i875/walrus2.jpg", "https://i.pinimg.com/originals/06/38/91/0638917eb3acc36d914fe4b8acef2f81.jpg"], 
},
];
